name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  tests:
    name: "Tests"
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1"
          - "lts"
          - "pre"
        os:
          - ubuntu-latest
        arch:
          - x64
        include:
          - version: "1.10"
            os: windows-latest
            arch: x64
          - version: "1.10"
            os: macOS-latest
            arch: x64
    uses: "SciML/.github/.github/workflows/tests.yml@v1"
    with:
      julia-version: "${{ matrix.version }}"
      julia-arch: "${{ matrix.arch }}"
      os: "${{ matrix.os }}"
    secrets: "inherit"
