name: Downgrade

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  downgrade:
    uses: "SciML/.github/.github/workflows/downgrade.yml@v1"
    with:
      julia-version: "lts"
    secrets: "inherit"
